import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
export default function Hero() {
    const navigate = useNavigate();
    const scrollToFeatures = () => {
        const el = document.getElementById('features');
        if (el)
            el.scrollIntoView({ behavior: 'smooth' });
    };
    return (_jsxs("section", { className: "pris-hero", id: "home", children: [_jsx("div", { className: "pris-hero__bg", "aria-hidden": "true" }), _jsxs("div", { className: "pris-hero__inner", children: [_jsxs("div", { className: "pris-hero__text", children: [_jsxs("div", { className: "pris-hero__badge", children: [_jsx("span", { className: "pris-hero__badge-dot" }), "AI-Powered Privacy Compliance"] }), _jsxs("h1", { className: "pris-hero__headline", children: ["See Every Risk.", _jsx("br", {}), _jsx("span", { children: "Prove Every" }), _jsx("br", {}), "Decision."] }), _jsx("p", { className: "pris-hero__sub", children: "Prismatic is an intelligent compliance platform that automatically scans, audits, and traces privacy regulations across your entire data ecosystem \u2014 powered by AI agents." }), _jsxs("div", { className: "pris-hero__ctas", children: [_jsxs("button", { id: "hero-get-started", className: "pris-btn pris-btn--primary pris-btn--large", onClick: () => navigate('/login'), children: ["Get Started Free", _jsxs("svg", { width: "16", height: "16", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2.5", strokeLinecap: "round", strokeLinejoin: "round", children: [_jsx("line", { x1: "5", y1: "12", x2: "19", y2: "12" }), _jsx("polyline", { points: "12 5 19 12 12 19" })] })] }), _jsx("button", { id: "hero-learn-more", className: "pris-btn pris-btn--ghost pris-btn--large", onClick: scrollToFeatures, children: "Learn More" })] }), _jsxs("div", { className: "pris-hero__stats", children: [_jsxs("div", { children: [_jsx("div", { className: "pris-hero__stat-num", children: "2.4M+" }), _jsx("div", { className: "pris-hero__stat-label", children: "Records Scanned" })] }), _jsx("div", { className: "pris-hero__stat-divider" }), _jsxs("div", { children: [_jsx("div", { className: "pris-hero__stat-num", children: "99.1%" }), _jsx("div", { className: "pris-hero__stat-label", children: "Audit Accuracy" })] }), _jsx("div", { className: "pris-hero__stat-divider" }), _jsxs("div", { children: [_jsx("div", { className: "pris-hero__stat-num", children: "12+" }), _jsx("div", { className: "pris-hero__stat-label", children: "Regulations Covered" })] })] })] }), _jsxs("div", { className: "pris-hero__shapes", "aria-hidden": "true", children: [_jsx("div", { className: "shape shape-1" }), _jsx("div", { className: "shape shape-2" }), _jsx("div", { className: "shape shape-3" }), _jsx("div", { className: "shape shape-4" }), _jsx("div", { className: "shape shape-5" }), _jsx("div", { className: "shape shape-6" }), _jsx("div", { className: "shape shape-7" }), _jsx("div", { className: "shape shape-8" }), _jsx("div", { className: "shape shape-9" })] })] })] }));
}
